export const UserData = {
    "id": "US001",
    "userName": "superadmin",
    "passwordHash": "string",
    "firstName": "Admin",
    "lastName": "User",
    "avatarUrl": "",
    "email": "superadmin@gmail.com",
    "phone": "+84123456789",
    "birthday": "1990-01-01",
    "address": "123 Main St",
    "status": 1,
    "role": 1,
    "isActive": true,
    "favoriteLocationsId": "string",
    "tripsId": "string",
    "createdAt": Date(),
    "updatedAt": Date()
}

export const LocationBlogList = [{
    id: "LB001",
    title: "Chuyến đi Sài Gòn - Vũng Tàu 2019",
    content: "Một chuyến đi tuyệt vời qua các địa điểm nổi tiếng tại Vũng Tàu, khám phá bãi biển đẹp và các điểm tham quan lịch sử. Thưởng thức hải sản tươi ngon và cảnh hoàng hôn tuyệt đẹp.",
    photos: ["https://via.placeholder.com/300x200?text=Vung+Tau+1", "https://via.placeholder.com/300x200?text=Vung+Tau+2"],
    position: "https://maps.app.goo.gl/e45EKXs4jQhq2SQs6",
    road: "QL51",
    startingId: "https://maps.app.goo.gl/zWNMX4tWTPh4smJR7",
    destinationId: "https://maps.app.goo.gl/jGUbfk4KDCwEb1C86",
    locationTags: ["#SaiGon", "#VungTau", "#BeachTrip", "#2019"],
    status: 1,
    isDraft: false,
    isActive: true,
    commentsId: [],
    ratingId: [],
    createdAt: Date(),
    updatedAt: Date(),
    createdBy: "John Doe",
    updatedBy: "John Doe",
}, {
    id: "LB002",
    title: "Hành trình Đà Nẵng - Hội An mùa xuân",
    content: "Khám phá thành phố cổ Hội An với những con phố đèn lồng, thăm viếng các di tích lịch sử và tham gia các hoạt động văn hóa truyền thống.",
    photos: ["https://via.placeholder.com/300x200?text=Hoi+An+1", "https://via.placeholder.com/300x200?text=Hoi+An+2", "https://via.placeholder.com/300x200?text=Hoi+An+3"],
    position: "https://maps.app.goo.gl/hoian",
    road: "QL1A",
    startingId: "https://maps.app.goo.gl/danang",
    destinationId: "https://maps.app.goo.gl/hoian",
    locationTags: ["#DaNang", "#HoiAn", "#CulturalTrip", "#Spring"],
    status: 1,
    isDraft: false,
    isActive: true,
    commentsId: [],
    ratingId: [],
    createdAt: Date(),
    updatedAt: Date(),
    createdBy: "Mary Jane",
    updatedBy: "Mary Jane",
}, {
    id: "LB003",
    title: "Phát hiện Sapa - Thị trấn mây mốc",
    content: "Trekking qua những cánh đồng lúa bậc thang, gặp gỡ các bộ tộc địa phương, và thưởng thức không khí se lạnh của vùng núi cao. Một trải nghiệm không thể quên.",
    photos: ["https://via.placeholder.com/300x200?text=Sapa+1", "https://via.placeholder.com/300x200?text=Sapa+2"],
    position: "https://maps.app.goo.gl/sapa",
    road: "QL4D",
    startingId: "https://maps.app.goo.gl/hanoi",
    destinationId: "https://maps.app.goo.gl/sapa",
    locationTags: ["#Sapa", "#Trekking", "#NorthernVietnam", "#Nature"],
    status: 1,
    isDraft: false,
    isActive: true,
    commentsId: [],
    ratingId: [],
    createdAt: Date(),
    updatedAt: Date(),
    createdBy: "Bob Smith",
    updatedBy: "Bob Smith",
}, {
    id: "LB004",
    title: "Hạ Long Bay - Kỳ quan thiên nhiên thế giới",
    content: "Khám phá Vịnh Hạ Long với những hòn đảo đá vôi kỳ bí, các hang động tuyệt đẹp và hoạt động thuyền buồm trên nước xanh ngọc. Một trải nghiệm không quên.",
    photos: ["https://via.placeholder.com/300x200?text=HaLong+1", "https://via.placeholder.com/300x200?text=HaLong+2", "https://via.placeholder.com/300x200?text=HaLong+3"],
    position: "https://maps.app.goo.gl/halong",
    road: "QL18",
    startingId: "https://maps.app.goo.gl/hanoi",
    destinationId: "https://maps.app.goo.gl/halong",
    locationTags: ["#HaLongBay", "#UNESCO", "#Cruise", "#NorthernVietnam"],
    status: 1,
    isDraft: false,
    isActive: true,
    commentsId: [],
    ratingId: [],
    createdAt: Date(),
    updatedAt: Date(),
    createdBy: "Sarah Wilson",
    updatedBy: "Sarah Wilson",
}, {
    id: "LB005",
    title: "Mekong Delta - Hành trình sông nước",
    content: "Khám phá đồng bằng sông Cửu Long với những thuyền nhỏ, chợi nổi truyền thống, vườn trái cây và ẩm thực địa phương độc đáo. Cảnh quang tuyệt vời về cuộc sống nông thôn.",
    photos: ["https://via.placeholder.com/300x200?text=Mekong+1", "https://via.placeholder.com/300x200?text=Mekong+2"],
    position: "https://maps.app.goo.gl/mekong",
    road: "QL1",
    startingId: "https://maps.app.goo.gl/saigon",
    destinationId: "https://maps.app.goo.gl/cantho",
    locationTags: ["#MekongDelta", "#RiverTour", "#LocalLife", "#FoodTrip"],
    status: 1,
    isDraft: false,
    isActive: true,
    commentsId: [],
    ratingId: [],
    createdAt: Date(),
    updatedAt: Date(),
    createdBy: "Michael Brown",
    updatedBy: "Michael Brown",
}, {
    id: "LB006",
    title: "Phú Quốc - Thiên đường biển đảo",
    content: "Thư giãn trên các bãi biển cát trắng, lặn biển khám phá san hô, thăm quần đảo xinh đẹp. Đây là điểm đến lý tưởng cho kỳ nghỉ thư giãn.",
    photos: ["https://via.placeholder.com/300x200?text=PhuQuoc+1", "https://via.placeholder.com/300x200?text=PhuQuoc+2", "https://via.placeholder.com/300x200?text=PhuQuoc+3"],
    position: "https://maps.app.goo.gl/phuquoc",
    road: "QL12",
    startingId: "https://maps.app.goo.gl/saigon",
    destinationId: "https://maps.app.goo.gl/phuquoc",
    locationTags: ["#PhuQuoc", "#Island", "#Beach", "#Diving"],
    status: 1,
    isDraft: false,
    isActive: true,
    commentsId: [],
    ratingId: [],
    createdAt: Date(),
    updatedAt: Date(),
    createdBy: "Emily Chen",
    updatedBy: "Emily Chen",
}, {
    id: "LB007",
    title: "Huế - Thủ đô cố đại của Việt Nam",
    content: "Khám phá kinh thành chua của Đại Việt, thăm viếng Lăng Tự Đức, Tử Cấm Thành và những di tích lịch sử đầy ý nghĩa. Thưởng thức ẩm thực Huế nổi tiếng.",
    photos: ["https://via.placeholder.com/300x200?text=Hue+1", "https://via.placeholder.com/300x200?text=Hue+2"],
    position: "https://maps.app.goo.gl/hue",
    road: "QL1A",
    startingId: "https://maps.app.goo.gl/danang",
    destinationId: "https://maps.app.goo.gl/hue",
    locationTags: ["#Hue", "#Imperial", "#History", "#Heritage"],
    status: 1,
    isDraft: false,
    isActive: true,
    commentsId: [],
    ratingId: [],
    createdAt: Date(),
    updatedAt: Date(),
    createdBy: "David Lee",
    updatedBy: "David Lee",
}, {
    id: "LB008",
    title: "Dalat - Thành phố ngàn hoa",
    content: "Khám phá thành phố Đà Lạt mát mẻ với những vườn hoa tuyệt đẹp, hồ Xuân Hương, chợ đêm sôi động. Tận hưởng không khí Tây Âu giữa lòng Tây Nguyên.",
    photos: ["https://via.placeholder.com/300x200?text=Dalat+1", "https://via.placeholder.com/300x200?text=Dalat+2", "https://via.placeholder.com/300x200?text=Dalat+3"],
    position: "https://maps.app.goo.gl/dalat",
    road: "QL20",
    startingId: "https://maps.app.goo.gl/tay+ninh",
    destinationId: "https://maps.app.goo.gl/dalat",
    locationTags: ["#Dalat", "#Flowers", "#Cool", "#TayNguyen"],
    status: 1,
    isDraft: false,
    isActive: true,
    commentsId: [],
    ratingId: [],
    createdAt: Date(),
    updatedAt: Date(),
    createdBy: "Jessica Nguyen",
    updatedBy: "Jessica Nguyen",
}, {
    id: "LB009",
    title: "Cát Bà - Đảo ngọc ở Hạ Long",
    content: "Hành trình khám phá đảo Cát Bà xinh đẹp với những bãi biển yên tĩnh, hang động kỳ bí và đỉnh núi Fansipan. Tuyệt vời cho những ai yêu thích trekking và sailing.",
    photos: ["https://via.placeholder.com/300x200?text=CatBa+1", "https://via.placeholder.com/300x200?text=CatBa+2"],
    position: "https://maps.app.goo.gl/catba",
    road: "QL18",
    startingId: "https://maps.app.goo.gl/haiphong",
    destinationId: "https://maps.app.goo.gl/catba",
    locationTags: ["#CatBa", "#Island", "#Hiking", "#Adventure"],
    status: 0,
    isDraft: true,
    isActive: true,
    commentsId: [],
    ratingId: [],
    createdAt: Date(),
    updatedAt: Date(),
    createdBy: "Chris Martin",
    updatedBy: "Chris Martin",
}, {
    id: "LB010",
    title: "Ninh Bình - Vịnh Ha Long trên cạn",
    content: "Khám phá Ninh Bình với những khối núi đá vôi chồng chất, tour kayak trên sông Ngo Dong, thăm Trang An và Tam Cốc. Cảnh quan thiên nhiên tuyệt đẹp.",
    photos: ["https://via.placeholder.com/300x200?text=NinhBinh+1", "https://via.placeholder.com/300x200?text=NinhBinh+2", "https://via.placeholder.com/300x200?text=NinhBinh+3"],
    position: "https://maps.app.goo.gl/ninhbinh",
    road: "QL1",
    startingId: "https://maps.app.goo.gl/hanoi",
    destinationId: "https://maps.app.goo.gl/ninhbinh",
    locationTags: ["#NinhBinh", "#Trang+An", "#TamCoc", "#Kayak"],
    status: 1,
    isDraft: false,
    isActive: true,
    commentsId: [],
    ratingId: [],
    createdAt: Date(),
    updatedAt: Date(),
    createdBy: "Olivia Jones",
    updatedBy: "Olivia Jones",
}]
export const LocationList = [{
    id: "LOC001",
    locationName: "Bãi biển Mỹ Khê",
    parentName: "Đà Nẵng",
    position: "https://maps.app.goo.gl/mykhebeach",
    tag: "#DaNang",
    photo: "https://via.placeholder.com/300x200?text=MyKheBeach"
}, {
    id: "LOC002",
    locationName: "Phố cổ Hội An",
    parentName: "Quảng Nam",
    position: "https://maps.app.goo.gl/hoian",
    tag: "#HoiAn",
    photo: "https://via.placeholder.com/300x200?text=HoiAn"
}, {
    id: "LOC003",
    locationName: "Sapa town",
    parentName: "Lào Cai",
    position: "https://maps.app.goo.gl/sapa",
    tag: "#Sapa",
    photo: "https://via.placeholder.com/300x200?text=Sapa"
}, {
    id: "LOC004",
    locationName: "Vịnh Hạ Long",
    parentName: "Quảng Ninh",
    position: "https://maps.app.goo.gl/halong",
    tag: "#HaLongBay",
    photo: "https://via.placeholder.com/300x200?text=HaLong"
}, {
    id: "LOC005",
    locationName: "Trang An",
    parentName: "Ninh Bình",
    position: "https://maps.app.goo.gl/trangan",
    tag: "#NinhBinh",
    photo: "https://via.placeholder.com/300x200?text=TrangAn"
}, {
    id: "LOC006",
    locationName: "Đảo Phú Quốc",
    parentName: "Kiên Giang",
    position: "https://maps.app.goo.gl/phuquoc",
    tag: "#PhuQuoc",
    photo: "https://via.placeholder.com/300x200?text=PhuQuoc"
}, {
    id: "LOC007",
    locationName: "Lăng Tự Đức",
    parentName: "Huế",
    position: "https://maps.app.goo.gl/tuduc",
    tag: "#Hue",
    photo: "https://via.placeholder.com/300x200?text=TuDuc"
}, {
    id: "LOC008",
    locationName: "Hồ Xuân Hương",
    parentName: "Đà Lạt",
    position: "https://maps.app.goo.gl/xuanhuong",
    tag: "#Dalat",
    photo: "https://via.placeholder.com/300x200?text=XuanHuong"
}, {
    id: "LOC009",
    locationName: "Đảo Cát Bà",
    parentName: "Hải Phòng",
    position: "https://maps.app.goo.gl/catba",
    tag: "#CatBa",
    photo: "https://via.placeholder.com/300x200?text=CatBa"
}, {
    id: "LOC010",
    locationName: "Thủy Tiên Beach",
    parentName: "Vũng Tàu",
    position: "https://maps.app.goo.gl/thuytien",
    tag: "#VungTau",
    photo: "https://via.placeholder.com/300x200?text=ThuyTien"
}, {
    id: "LOC011",
    locationName: "Chợ nổi Cái Răng",
    parentName: "Cần Thơ",
    position: "https://maps.app.goo.gl/cairang",
    tag: "#MekongDelta",
    photo: "https://via.placeholder.com/300x200?text=CaiRang"
}, {
    id: "LOC012",
    locationName: "Tử Cấm Thành",
    parentName: "Huế",
    position: "https://maps.app.goo.gl/citadel",
    tag: "#Hue",
    photo: "https://via.placeholder.com/300x200?text=Citadel"
}, {
    id: "LOC013",
    locationName: "Núi Bà",
    parentName: "Tây Ninh",
    position: "https://maps.app.goo.gl/nuiba",
    tag: "#TayNinh",
    photo: "https://via.placeholder.com/300x200?text=NuiBa"
}, {
    id: "LOC014",
    locationName: "Hội An Beach",
    parentName: "Quảng Nam",
    position: "https://maps.app.goo.gl/hoianbeach",
    tag: "#HoiAn",
    photo: "https://via.placeholder.com/300x200?text=HoiAnBeach"
}, {
    id: "LOC015",
    locationName: "Tam Cốc",
    parentName: "Ninh Bình",
    position: "https://maps.app.goo.gl/tamcoc",
    tag: "#NinhBinh",
    photo: "https://via.placeholder.com/300x200?text=TamCoc"
}]
export const UserListData = [{
    "id": "US001",
    "userName": "superadmin",
    "passwordHash": "string",
    "firstName": "Admin",
    "lastName": "User",
    "avatarUrl": "https://api.dicebear.com/7.x/avataaars/svg?seed=superadmin",
    "email": "superadmin@gmail.com",
    "phone": "+84123456789",
    "birthday": "1990-01-01",
    "address": "123 Main St",
    "status": 1,
    "role": 1,
    "isActive": true,
    "favoriteLocationsId": "string",
    "tripsId": "string",
    "createdAt": Date(),
    "updatedAt": Date()
},
{
    "id": "US002",
    "userName": "johndoe",
    "passwordHash": "string",
    "firstName": "John",
    "lastName": "Doe",
    "avatarUrl": "https://api.dicebear.com/7.x/avataaars/svg?seed=johndoe",
    "email": "john.doe@gmail.com",
    "phone": "+84912345678",
    "birthday": "1988-05-15",
    "address": "456 Oak Ave",
    "status": 1,
    "role": 2,
    "isActive": true,
    "favoriteLocationsId": "string",
    "tripsId": "string",
    "createdAt": Date(),
    "updatedAt": Date()
},
{
    "id": "US003",
    "userName": "maryjane",
    "passwordHash": "string",
    "firstName": "Mary",
    "lastName": "Jane",
    "avatarUrl": "https://api.dicebear.com/7.x/avataaars/svg?seed=maryjane",
    "email": "mary.jane@gmail.com",
    "phone": "+84987654321",
    "birthday": "1992-08-22",
    "address": "789 Pine Rd",
    "status": 1,
    "role": 2,
    "isActive": true,
    "favoriteLocationsId": "string",
    "tripsId": "string",
    "createdAt": Date(),
    "updatedAt": Date()
},
{
    "id": "US004",
    "userName": "bobsmith",
    "passwordHash": "string",
    "firstName": "Bob",
    "lastName": "Smith",
    "avatarUrl": "https://api.dicebear.com/7.x/avataaars/svg?seed=bobsmith",
    "email": "bob.smith@gmail.com",
    "phone": "+84856341920",
    "birthday": "1985-03-10",
    "address": "321 Elm St",
    "status": 1,
    "role": 2,
    "isActive": true,
    "favoriteLocationsId": "string",
    "tripsId": "string",
    "createdAt": Date(),
    "updatedAt": Date()
},
{
    "id": "US005",
    "userName": "sarahwilson",
    "passwordHash": "string",
    "firstName": "Sarah",
    "lastName": "Wilson",
    "avatarUrl": "https://api.dicebear.com/7.x/avataaars/svg?seed=sarahwilson",
    "email": "sarah.wilson@gmail.com",
    "phone": "+84765432109",
    "birthday": "1991-12-05",
    "address": "654 Maple Dr",
    "status": 1,
    "role": 2,
    "isActive": true,
    "favoriteLocationsId": "string",
    "tripsId": "string",
    "createdAt": Date(),
    "updatedAt": Date()
},
{
    "id": "US006",
    "userName": "michaelbrown",
    "passwordHash": "string",
    "firstName": "Michael",
    "lastName": "Brown",
    "avatarUrl": "https://api.dicebear.com/7.x/avataaars/svg?seed=michaelbrown",
    "email": "michael.brown@gmail.com",
    "phone": "+84654321098",
    "birthday": "1987-06-18",
    "address": "987 Birch Ln",
    "status": 1,
    "role": 2,
    "isActive": true,
    "favoriteLocationsId": "string",
    "tripsId": "string",
    "createdAt": Date(),
    "updatedAt": Date()
},
{
    "id": "US007",
    "userName": "emilychen",
    "passwordHash": "string",
    "firstName": "Emily",
    "lastName": "Chen",
    "avatarUrl": "https://api.dicebear.com/7.x/avataaars/svg?seed=emilychen",
    "email": "emily.chen@gmail.com",
    "phone": "+84543210987",
    "birthday": "1993-09-30",
    "address": "246 Cedar Way",
    "status": 1,
    "role": 2,
    "isActive": true,
    "favoriteLocationsId": "string",
    "tripsId": "string",
    "createdAt": Date(),
    "updatedAt": Date()
},
{
    "id": "US008",
    "userName": "davidlee",
    "passwordHash": "string",
    "firstName": "David",
    "lastName": "Lee",
    "avatarUrl": "https://api.dicebear.com/7.x/avataaars/svg?seed=davidlee",
    "email": "david.lee@gmail.com",
    "phone": "+84432109876",
    "birthday": "1989-02-14",
    "address": "135 Spruce St",
    "status": 1,
    "role": 2,
    "isActive": true,
    "favoriteLocationsId": "string",
    "tripsId": "string",
    "createdAt": Date(),
    "updatedAt": Date()
},
{
    "id": "US009",
    "userName": "jessicangu",
    "passwordHash": "string",
    "firstName": "Jessica",
    "lastName": "Nguyen",
    "avatarUrl": "https://api.dicebear.com/7.x/avataaars/svg?seed=jessicangu",
    "email": "jessica.nguyen@gmail.com",
    "phone": "+84321098765",
    "birthday": "1994-07-25",
    "address": "579 Willow Ct",
    "status": 1,
    "role": 2,
    "isActive": true,
    "favoriteLocationsId": "string",
    "tripsId": "string",
    "createdAt": Date(),
    "updatedAt": Date()
},
{
    "id": "US010",
    "userName": "chrismartin",
    "passwordHash": "string",
    "firstName": "Chris",
    "lastName": "Martin",
    "avatarUrl": "https://api.dicebear.com/7.x/avataaars/svg?seed=chrismartin",
    "email": "chris.martin@gmail.com",
    "phone": "+84210987654",
    "birthday": "1986-11-08",
    "address": "802 Oak Ridge",
    "status": 1,
    "role": 2,
    "isActive": true,
    "favoriteLocationsId": "string",
    "tripsId": "string",
    "createdAt": Date(),
    "updatedAt": Date()
},
{
    "id": "US011",
    "userName": "sophiadavis",
    "passwordHash": "string",
    "firstName": "Sophia",
    "lastName": "Davis",
    "avatarUrl": "https://api.dicebear.com/7.x/avataaars/svg?seed=sophiadavis",
    "email": "sophia.davis@gmail.com",
    "phone": "+84109876543",
    "birthday": "1995-04-19",
    "address": "413 Sunset Blvd",
    "status": 0,
    "role": 2,
    "isActive": false,
    "favoriteLocationsId": "string",
    "tripsId": "string",
    "createdAt": Date(),
    "updatedAt": Date()
},
{
    "id": "US012",
    "userName": "jameswilliams",
    "passwordHash": "string",
    "firstName": "James",
    "lastName": "Williams",
    "avatarUrl": "https://api.dicebear.com/7.x/avataaars/svg?seed=jameswilliams",
    "email": "james.williams@gmail.com",
    "phone": "+84987654310",
    "birthday": "1984-01-12",
    "address": "567 Mountain View",
    "status": 1,
    "role": 2,
    "isActive": true,
    "favoriteLocationsId": "string",
    "tripsId": "string",
    "createdAt": Date(),
    "updatedAt": Date()
},
{
    "id": "US013",
    "userName": "oliviajones",
    "passwordHash": "string",
    "firstName": "Olivia",
    "lastName": "Jones",
    "avatarUrl": "https://api.dicebear.com/7.x/avataaars/svg?seed=oliviajones",
    "email": "olivia.jones@gmail.com",
    "phone": "+84876543210",
    "birthday": "1990-10-27",
    "address": "890 Valley Rd",
    "status": 1,
    "role": 2,
    "isActive": true,
    "favoriteLocationsId": "string",
    "tripsId": "string",
    "createdAt": Date(),
    "updatedAt": Date()
},
{
    "id": "US014",
    "userName": "williamgarcia",
    "passwordHash": "string",
    "firstName": "William",
    "lastName": "Garcia",
    "avatarUrl": "https://api.dicebear.com/7.x/avataaars/svg?seed=williamgarcia",
    "email": "william.garcia@gmail.com",
    "phone": "+84765432198",
    "birthday": "1988-09-03",
    "address": "724 River Lane",
    "status": 1,
    "role": 2,
    "isActive": true,
    "favoriteLocationsId": "string",
    "tripsId": "string",
    "createdAt": Date(),
    "updatedAt": Date()
},
{
    "id": "US015",
    "userName": "avamiller",
    "passwordHash": "string",
    "firstName": "Ava",
    "lastName": "Miller",
    "avatarUrl": "https://api.dicebear.com/7.x/avataaars/svg?seed=avamiller",
    "email": "ava.miller@gmail.com",
    "phone": "+84654321987",
    "birthday": "1996-06-16",
    "address": "356 Forest Crest",
    "status": 1,
    "role": 2,
    "isActive": true,
    "favoriteLocationsId": "string",
    "tripsId": "string",
    "createdAt": Date(),
    "updatedAt": Date()
},
{
    "id": "US016",
    "userName": "liamanderson",
    "passwordHash": "string",
    "firstName": "Liam",
    "lastName": "Anderson",
    "avatarUrl": "https://api.dicebear.com/7.x/avataaars/svg?seed=liamanderson",
    "email": "liam.anderson@gmail.com",
    "phone": "+84543219876",
    "birthday": "1991-03-21",
    "address": "468 Meadow View",
    "status": 1,
    "role": 2,
    "isActive": true,
    "favoriteLocationsId": "string",
    "tripsId": "string",
    "createdAt": Date(),
    "updatedAt": Date()
},
{
    "id": "US017",
    "userName": "miasthompson",
    "passwordHash": "string",
    "firstName": "Mia",
    "lastName": "Thompson",
    "avatarUrl": "https://api.dicebear.com/7.x/avataaars/svg?seed=miasthompson",
    "email": "mia.thompson@gmail.com",
    "phone": "+84432198765",
    "birthday": "1993-11-09",
    "address": "591 Lakeside Dr",
    "status": 1,
    "role": 2,
    "isActive": true,
    "favoriteLocationsId": "string",
    "tripsId": "string",
    "createdAt": Date(),
    "updatedAt": Date()
},
{
    "id": "US018",
    "userName": "ethanwhite",
    "passwordHash": "string",
    "firstName": "Ethan",
    "lastName": "White",
    "avatarUrl": "https://api.dicebear.com/7.x/avataaars/svg?seed=ethanwhite",
    "email": "ethan.white@gmail.com",
    "phone": "+84321987654",
    "birthday": "1987-08-14",
    "address": "703 Sunny Lane",
    "status": 1,
    "role": 2,
    "isActive": true,
    "favoriteLocationsId": "string",
    "tripsId": "string",
    "createdAt": Date(),
    "updatedAt": Date()
},
{
    "id": "US019",
    "userName": "isabellaharris",
    "passwordHash": "string",
    "firstName": "Isabella",
    "lastName": "Harris",
    "avatarUrl": "https://api.dicebear.com/7.x/avataaars/svg?seed=isabellaharris",
    "email": "isabella.harris@gmail.com",
    "phone": "+84210876543",
    "birthday": "1994-12-28",
    "address": "815 Quiet St",
    "status": 1,
    "role": 2,
    "isActive": true,
    "favoriteLocationsId": "string",
    "tripsId": "string",
    "createdAt": Date(),
    "updatedAt": Date()
},
{
    "id": "US020",
    "userName": "lucasmartin",
    "passwordHash": "string",
    "firstName": "Lucas",
    "lastName": "Martin",
    "avatarUrl": "https://api.dicebear.com/7.x/avataaars/svg?seed=lucasmartin",
    "email": "lucas.martin@gmail.com",
    "phone": "+84109765432",
    "birthday": "1989-05-07",
    "address": "927 Peace Ave",
    "status": 1,
    "role": 2,
    "isActive": true,
    "favoriteLocationsId": "string",
    "tripsId": "string",
    "createdAt": Date(),
    "updatedAt": Date()
}]