export const UserData = {
    "id": "US001",
    "userName": "superadmin",
    "passwordHash": "string",
    "firstName": "Admin",
    "lastName": "User",
    "avatarUrl": "",
    "email": "superadmin@gmail.com",
    "phone": "+84123456789",
    "birthday": "1990-01-01",
    "address": "123 Main St",
    "status": 1,
    "role": 1,
    "isActive": true,
    "favoriteLocationsId": "string",
    "tripsId": "string",
    "createdAt": Date(),
    "updatedAt": Date()
}

export const LocationBlogList = [{
    id: "LB001",
    title: "Chuyến đi 2019",
    content: "Nội dung bài viết...",
    photos: [],
    position: "https://maps.app.goo.gl/e45EKXs4jQhq2SQs6",
    road: "QL51",
    startingId: "https://maps.app.goo.gl/zWNMX4tWTPh4smJR7",
    destinationId: "https://maps.app.goo.gl/jGUbfk4KDCwEb1C86",
    locationTags: ["#Saigon", "#Dongnai", "#Vungtau"],
    status: 1,
    isDraft: false,
    isActive: true,
    commentsId: [],
    ratingId: [],
    createdAt: Date(),
    updatedAt: Date(),
    createdBy: "Khang",
    updatedBy: "Khang",
}, {
    id: "LB002",
    title: "Chuyến đi 2020",
    content: "Nội dung bài viết...",
    photos: [],
    position: "https://maps.app.goo.gl/e45EKXs4jQhq2SQs6",
    road: "QL51",
    startingId: "https://maps.app.goo.gl/zWNMX4tWTPh4smJR7",
    destinationId: "https://maps.app.goo.gl/jGUbfk4KDCwEb1C86",
    locationTags: ["#Saigon", "#Dongnai", "#Vungtau"],
    status: 1,
    isDraft: false,
    isActive: true,
    commentsId: [],
    ratingId: [],
    createdAt: Date(),
    updatedAt: Date(),
    createdBy: "Khang",
    updatedBy: "Khang",
}, {
    id: "LB001",
    title: "Chuyến đi 2021",
    content: "Nội dung bài viết...",
    photos: [],
    position: "https://maps.app.goo.gl/e45EKXs4jQhq2SQs6",
    road: "QL51",
    startingId: "https://maps.app.goo.gl/zWNMX4tWTPh4smJR7",
    destinationId: "https://maps.app.goo.gl/jGUbfk4KDCwEb1C86",
    locationTags: ["#Saigon", "#Dongnai", "#Vungtau"],
    status: 1,
    isDraft: false,
    isActive: true,
    commentsId: [],
    ratingId: [],
    createdAt: Date(),
    updatedAt: Date(),
    createdBy: "Khang",
    updatedBy: "Khang",
}]
